/* Formatted on 2007/10/15 00:04 (QP5 v5.50) */
CREATE TABLE `contact` (
  `contact_id` int(11) NOT NULL auto_increment,
  `contact_name` varchar(50) NOT NULL,
  `first_name` varchar(20) NOT NULL,
  `middle_name` varchar(20) default NULL,
  `last_name` varchar(20) default NULL,
  `num_referrals` int(11) default NULL,
  `num_tickets` int(11) default NULL,
  `num_open_tickets` int(11) default NULL,
  `num_queries` int(11) default NULL,
  `dues` decimal(10,0) default NULL,
  `insert_key` varchar(30) default NULL,
  `phone_work` varchar(20) default NULL,
  `phone_cell` varchar(20) default NULL,
  `phone_home` varchar(20) default NULL,
  `email_home` varchar(40) default NULL,
  `email_work` varchar(40) default NULL,
  `address_line1_home` varchar(200) default NULL,
  `address_line2_home` varchar(200) default NULL,
  `address_line3_home` varchar(200) default NULL,
  `city_home` varchar(50) default NULL,
  `state_home` varchar(50) default NULL,
  `zip_home` varchar(20) default NULL,
  `country_home` varchar(50) default NULL,
  `address_line1_work` varchar(200) NOT NULL,
  `address_line2_work` varchar(200) default NULL,
  `address_line3_work` varchar(200) default NULL,
  `city_work` varchar(50) default NULL,
  `state_work` varchar(50) default NULL,
  `zip_work` varchar(50) default NULL,
  `country_work` varchar(50) default NULL,
  `contact_type` varchar(20) default NULL,
  `deleted` int(11) default NULL,
  `add_dttm` datetime default NULL,
  `update_dttm` datetime default NULL,
  `delete_dttm` datetime default NULL,
  `status` varchar(50) default NULL,
  `referer_id` int(11) default NULL,
  `notes` varchar(5000) default NULL,
  `num_itineraries` int(11) default NULL,
  `created_by` varchar(20) default NULL,
  `updated_by` varchar(20) default NULL,
  `agent_assigned` varchar(20) default NULL,
  `status_history` varchar(2000) default NULL,
  PRIMARY KEY  (`contact_id`)
) ENGINE=MyISAM AUTO_INCREMENT=48 DEFAULT CHARSET=latin1;

