/* Formatted on 2007/10/14 21:07 (QP5 v5.50) */
CREATE TABLE `itinerary_request` (
  `request_id` int(11) NOT NULL auto_increment,
  `customer_id` int(11) NOT NULL,
  `pax1_first_name` varchar(30) default NULL,
  `pax1_last_name` varchar(30) default NULL,
  `pax1_title` varchar(20) default NULL,
  `pax1_age` decimal(10,0) default NULL,
  `pax2_first_name` varchar(30) default NULL,
  `pax2_last_name` varchar(30) default NULL,
  `pax2_title` varchar(20) default NULL,
  `pax2_age` decimal(10,0) default NULL,
  `pax3_first_name` varchar(30) default NULL,
  `pax3_last_name` varchar(30) default NULL,
  `pax3_title` varchar(20) default NULL,
  `pax3_age` decimal(10,0) default NULL,
  `pax4_first_name` varchar(30) default NULL,
  `pax4_last_name` varchar(30) default NULL,
  `pax4_title` varchar(20) default NULL,
  `pax4_age` decimal(10,0) default NULL,
  `pax5_first_name` varchar(30) default NULL,
  `pax5_last_name` varchar(30) default NULL,
  `pax5_title` varchar(20) default NULL,
  `pax5_age` decimal(10,0) default NULL,
  `num_calls` int(11) default NULL,
  `insert_key` varchar(20) default NULL,
  `deleted` int(11) default NULL,
  `add_dttm` datetime default NULL,
  `update_dttm` datetime default NULL,
  `delete_dttm` datetime default NULL,
  `created_by` varchar(20) default NULL,
  `updated_by` varchar(20) default NULL,
  `num_itinerary` int(11) default NULL,
  `depart_date` varchar(20) default NULL,
  `return_date` varchar(20) default NULL,
  `primary_airline` varchar(20) default NULL,
  `num_tickets` int(11) default NULL,
  `depart_airport` varchar(20) default NULL,
  `arrive_airport` varchar(20) default NULL,
  `notes` varchar(500) default NULL,
  `pax1_middle_name` varchar(30) default NULL,
  `pax2_middle_name` varchar(30) default NULL,
  `pax3_middle_name` varchar(30) default NULL,
  `pax4_middle_name` varchar(30) default NULL,
  `pax5_middle_name` varchar(30) default NULL,
  `contact_name` varchar(20) default NULL,
  `request_type` varchar(50) default NULL,
  `email_home` varchar(50) default NULL,
  `phone_work` varchar(20) default NULL,
  `flexible_dates_airports` varchar(200) default NULL,
  `prefer_avoid_airlines_airports` varchar(200) default NULL,
  PRIMARY KEY  (`request_id`),
  KEY `contact_id` (`customer_id`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

